// <auto-generated />
using System;
using LogManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogManager.Data.Migrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20231126175904_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogManager.Core.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("LogManager.Core.Models.LogMessage", b =>
                {
                    b.Property<int>("LogMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogMessageId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageLog")
                        .HasColumnType("text");

                    b.HasKey("LogMessageId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("LoggerMessage");
                });

            modelBuilder.Entity("LogManager.Core.Models.LogMessage", b =>
                {
                    b.HasOne("LogManager.Core.Models.Application", "Application")
                        .WithMany("LogMessages")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("LogManager.Core.Models.Application", b =>
                {
                    b.Navigation("LogMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
